// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order-mg/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, input
func (_m *OrderService) CreateOrder(ctx context.Context, input model.Order) (model.Order, error) {
	ret := _m.Called(ctx, input)

	var r0 model.Order
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) model.Order); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Order) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOrder provides a mock function with given fields: ctx, orderID
func (_m *OrderService) DeleteOrder(ctx context.Context, orderID int64) error {
	ret := _m.Called(ctx, orderID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderByID provides a mock function with given fields: ctx, orderID
func (_m *OrderService) GetOrderByID(ctx context.Context, orderID int64) (model.Order, error) {
	ret := _m.Called(ctx, orderID)

	var r0 model.Order
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Order); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrders provides a mock function with given fields: ctx, limit, lastID
func (_m *OrderService) GetOrders(ctx context.Context, limit int, lastID int64) ([]model.Order, error) {
	ret := _m.Called(ctx, limit, lastID)

	var r0 []model.Order
	if rf, ok := ret.Get(0).(func(context.Context, int, int64) []model.Order); ok {
		r0 = rf(ctx, limit, lastID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int64) error); ok {
		r1 = rf(ctx, limit, lastID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrder provides a mock function with given fields: ctx, input, orderID
func (_m *OrderService) UpdateOrder(ctx context.Context, input model.Order, orderID int64) (model.Order, error) {
	ret := _m.Called(ctx, input, orderID)

	var r0 model.Order
	if rf, ok := ret.Get(0).(func(context.Context, model.Order, int64) model.Order); ok {
		r0 = rf(ctx, input, orderID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Order, int64) error); ok {
		r1 = rf(ctx, input, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewOrderService interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderService(t mockConstructorTestingTNewOrderService) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
