// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order-mg/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, _a1
func (_m *UserRepository) CreateUser(ctx context.Context, _a1 model.Users) (model.Users, error) {
	ret := _m.Called(ctx, _a1)

	var r0 model.Users
	if rf, ok := ret.Get(0).(func(context.Context, model.Users) model.Users); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Users)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Users) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *UserRepository) DeleteUser(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *UserRepository) GetUserByID(ctx context.Context, userID int64) (model.Users, error) {
	ret := _m.Called(ctx, userID)

	var r0 model.Users
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Users); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.Users)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, limit, lastID
func (_m *UserRepository) GetUsers(ctx context.Context, limit int, lastID int64) ([]model.Users, error) {
	ret := _m.Called(ctx, limit, lastID)

	var r0 []model.Users
	if rf, ok := ret.Get(0).(func(context.Context, int, int64) []model.Users); ok {
		r0 = rf(ctx, limit, lastID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Users)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int64) error); ok {
		r1 = rf(ctx, limit, lastID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, _a1
func (_m *UserRepository) UpdateUser(ctx context.Context, _a1 model.Users) (model.Users, error) {
	ret := _m.Called(ctx, _a1)

	var r0 model.Users
	if rf, ok := ret.Get(0).(func(context.Context, model.Users) model.Users); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Users)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Users) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
